### ISSUE TITLE
About the PR curve data points

### ISSUE THREAD

**Issue by speedcell4** [allenai/comb_direct_dist_relex#1]
Hi~ thanks for publishing your code.
Could you please also publish your PR curve data points like what the [RESIDE](https://github.com/malllabiisc/RESIDE/tree/master/baselines_pr/riedel_nyt) did. I think that will make the successors easy to compare their new models with yours when they want to plot both their and your results. Thanks~

**Comment by ibeltagy** [comment]
Please check https://github.com/allenai/comb_dist_direct_relex/blob/master/scripts/plot_pr_curves.py
